---
name: Demo pipeline stdin
variables: ~
stages:
  get_source:
    command: cat /dev/stdin
  validate:
    command: xmllint --schema rss-2_0.xsd -
  transform:
    command: xsltproc rss2html.xslt -
  pretty:
    command: xsltproc pretty.xslt -
